# go2rtc config for live cameras

streams:
  cam-01:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.32:554/Streaming/Channels/102
  cam-02:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.16:554/Streaming/Channels/102
  cam-03:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.46:554/Streaming/Channels/102
  cam-04:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.44:554/Streaming/Channels/102
  cam-05:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.17:554/Streaming/Channels/102
  cam-06:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.18:554/Streaming/Channels/102
  cam-16:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.20:554/Streaming/Channels/102
  cam-18:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.28:554/Streaming/Channels/102
  cam-20:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.22:554/Streaming/Channels/102
  cam-21:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.48:554/Streaming/Channels/102
  cam-22:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.24:554/Streaming/Channels/102
  cam-23:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.29:554/Streaming/Channels/102
  cam-24:
    - rtsp://admin:Zxcv2Zxcv2@10.223.70.45:554/Streaming/Channels/102

api:
  origin: "*"

webrtc:
  candidates:
    - 127.0.0.1
    - stun:stun.l.google.com:19302
