#!/usr/bin/env python3
"""generate_dinov2_prototypes_h.py — emit C++ header with hardcoded
DINOv2 4-class prototypes (L2-normalized FP32 [4, 768]).

Source: ~/race_vision_bench/dinov2_prod/prototypes_dinov2_v1.npz
Target: deepstream/src/dinov2_prototypes_v1.h
"""
from __future__ import annotations
from pathlib import Path
import numpy as np

REPO = Path(__file__).resolve().parent.parent
SRC = Path("/home/ipodrom/race_vision_bench/dinov2_prod/prototypes_dinov2_v1.npz")
DST = REPO / "deepstream" / "src" / "dinov2_prototypes_v1.h"

# labels_color.txt: blue=0, green=1, purple=2, red=3, yellow=4
LABELS_COLOR_TXT_INDEX = {"blue": 0, "green": 1, "purple": 2, "red": 3, "yellow": 4}


def main():
    data = np.load(SRC, allow_pickle=False)
    protos  = data["prototypes"].astype(np.float32)   # [4, 768]
    classes = [str(c) for c in data["classes"]]        # ['green','yellow','red','blue']
    assert protos.shape == (4, 768), f"unexpected shape {protos.shape}"
    assert classes == ["green", "yellow", "red", "blue"], f"unexpected order {classes}"

    # verify L2-normalized
    norms = np.linalg.norm(protos, axis=1)
    assert np.allclose(norms, 1.0, atol=1e-5), f"prototypes not L2-norm: {norms}"

    # mapping our_idx → labels_color.txt class_id
    mapping = [LABELS_COLOR_TXT_INDEX[c] for c in classes]   # [1, 4, 3, 0]

    out = []
    out.append("#pragma once")
    out.append("// AUTO-GENERATED by tools/generate_dinov2_prototypes_h.py")
    out.append(f"// Source: {SRC.name}")
    out.append("// Built from cam-24 video (yaris_20260421_135242/kamera_24_135253_END135443.mp4)")
    out.append("// Labels: 50 blue + 53 green + 53 yellow + 60 red (216 jockey crops)")
    out.append("// L2-normalized FP32, shape [4, 768]")
    out.append("// DO NOT EDIT — re-run the generator to refresh.")
    out.append("")
    out.append("namespace rv {")
    out.append("")
    out.append("constexpr int DINOV2_NUM_PROTOS = 4;")
    out.append("constexpr int DINOV2_DIM = 768;")
    out.append("")
    out.append("// Our prototype order (matches model output decision)")
    out.append("static const char* kDinov2ProtoLabels[DINOV2_NUM_PROTOS] = {")
    for c in classes:
        out.append(f'    "{c}",')
    out.append("};")
    out.append("")
    out.append("// Mapping our prototype index → labels_color.txt class_id")
    out.append("// labels_color.txt order: blue=0, green=1, purple=2, red=3, yellow=4")
    out.append("static const unsigned int kDinov2ClassMapping[DINOV2_NUM_PROTOS] = {")
    for cls, idx in zip(classes, mapping):
        out.append(f"    {idx}u,  // {cls}")
    out.append("};")
    out.append("")
    out.append("// Prototypes (L2-normalized, FP32)")
    out.append("static const float kDinov2Protos[DINOV2_NUM_PROTOS][DINOV2_DIM] = {")
    for i, cls in enumerate(classes):
        out.append(f"    /* {cls} */ {{")
        # 6 floats per line for readability
        floats = [f"{x:.7g}f" for x in protos[i]]
        for j in range(0, len(floats), 6):
            line = ", ".join(floats[j:j+6])
            suffix = "," if j + 6 < len(floats) else ""
            out.append(f"        {line}{suffix}")
        end = "}," if i < len(classes) - 1 else "}"
        out.append(f"    {end}")
    out.append("};")
    out.append("")
    out.append("} // namespace rv")
    out.append("")

    DST.write_text("\n".join(out))
    print(f"Wrote {DST}  ({DST.stat().st_size / 1024:.1f} KB)")
    print(f"  prototypes: {protos.shape}")
    print(f"  order:      {classes}")
    print(f"  mapping:    {mapping}  (our_idx → labels_color.txt id)")


if __name__ == "__main__":
    main()
