#!/usr/bin/env python3
"""generate_osnet_prototypes_h.py — emit C++ header with hardcoded
OSNet 4-class prototypes (L2-normalized FP32 [4, 512]).

Source: ~/race_vision_bench/osnet_test/prototypes_osnet_combined.npz
        (1444 crops, 17 cams, 5 sessions; multicam + color_dataset
        merged; 4 classes blue/green/red/yellow)
Target: deepstream/src/osnet_prototypes_v1.h

Source order in .npz: ['blue','green','red','yellow'] (alphabetical from
build_prototypes.py). The header reorders to [green, yellow, red, blue]
to keep DINOv2 parser layout (kClassMapping = [1,4,3,0]).
"""
from __future__ import annotations
from pathlib import Path
import numpy as np

REPO = Path(__file__).resolve().parent.parent
SRC = Path("/home/ipodrom/race_vision_bench/osnet_test/prototypes_osnet_combined.npz")
DST = REPO / "deepstream" / "src" / "osnet_prototypes_v1.h"

# Final order in the header (matches DINOv2 layout for parser symmetry)
TARGET_ORDER = ["green", "yellow", "red", "blue"]

# labels_color.txt: blue=0, green=1, purple=2, red=3, yellow=4
LABELS_COLOR_TXT_INDEX = {"blue": 0, "green": 1, "purple": 2, "red": 3, "yellow": 4}


def main():
    data = np.load(SRC, allow_pickle=False)
    src_protos = data["prototypes"].astype(np.float32)        # [4, 512]
    src_classes = [str(c) for c in data["classes"]]            # ['blue','green','red','yellow']
    assert src_protos.shape == (4, 512), f"unexpected shape {src_protos.shape}"
    assert set(src_classes) == set(TARGET_ORDER), f"class set mismatch: {src_classes}"

    # Reorder rows to TARGET_ORDER
    idx = [src_classes.index(c) for c in TARGET_ORDER]
    protos = src_protos[idx]
    classes = TARGET_ORDER

    # Verify L2-normalized
    norms = np.linalg.norm(protos, axis=1)
    assert np.allclose(norms, 1.0, atol=1e-5), f"prototypes not L2-norm: {norms}"

    mapping = [LABELS_COLOR_TXT_INDEX[c] for c in classes]   # [1, 4, 3, 0]

    out = []
    out.append("#pragma once")
    out.append("// AUTO-GENERATED by tools/generate_osnet_prototypes_h.py")
    out.append(f"// Source: {SRC.name}")
    out.append("// Generated from prototypes_osnet_combined.npz, 1444 crops × 17 cams × 5 sessions")
    out.append("// Classes: 205 blue + 379 green + 433 red + 427 yellow (combined: multicam + color_dataset)")
    out.append("// Backbone: osnet_x1_0 pretrained on Market1501; L2-normalized FP32, shape [4, 512]")
    out.append("// DO NOT EDIT — re-run the generator to refresh.")
    out.append("")
    out.append("namespace rv {")
    out.append("")
    out.append("constexpr int OSNET_NUM_PROTOS = 4;")
    out.append("constexpr int OSNET_DIM = 512;")
    out.append("")
    out.append("// Our prototype order (matches model output decision)")
    out.append("static const char* kOsnetProtoLabels[OSNET_NUM_PROTOS] = {")
    for c in classes:
        out.append(f'    "{c}",')
    out.append("};")
    out.append("")
    out.append("// Mapping our prototype index → labels_color.txt class_id")
    out.append("// labels_color.txt order: blue=0, green=1, purple=2, red=3, yellow=4")
    out.append("static const unsigned int kOsnetClassMapping[OSNET_NUM_PROTOS] = {")
    for cls, m in zip(classes, mapping):
        out.append(f"    {m}u,  // {cls}")
    out.append("};")
    out.append("")
    out.append("// Prototypes (L2-normalized, FP32)")
    def fmt_float(x: float) -> str:
        # %g may print "0" or "1" for integer-valued floats; force a decimal so
        # the output is a valid C++ float literal (e.g. "0.0f", "1.0f").
        s = f"{x:.7g}"
        if "e" not in s and "." not in s:
            s += ".0"
        return s + "f"

    out.append("static const float kOsnetProtos[OSNET_NUM_PROTOS][OSNET_DIM] = {")
    for i, cls in enumerate(classes):
        out.append(f"    /* {cls} */ {{")
        floats = [fmt_float(x) for x in protos[i]]
        for j in range(0, len(floats), 6):
            line = ", ".join(floats[j:j+6])
            suffix = "," if j + 6 < len(floats) else ""
            out.append(f"        {line}{suffix}")
        end = "}," if i < len(classes) - 1 else "}"
        out.append(f"    {end}")
    out.append("};")
    out.append("")
    out.append("} // namespace rv")
    out.append("")

    DST.write_text("\n".join(out))
    print(f"Wrote {DST}  ({DST.stat().st_size / 1024:.1f} KB)")
    print(f"  prototypes: {protos.shape}")
    print(f"  order:      {classes}")
    print(f"  mapping:    {mapping}  (our_idx → labels_color.txt id)")


if __name__ == "__main__":
    main()
